<a href="https://colab.research.google.com/github/Nishith2001/Training-and-testing-data/blob/main/Linear%20Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/LSM1.csv")

In [ ]:
df

X  Y
0  1  2
1  2  4
2  3  5
3  4  4
4  5  5

In [ ]:
x = df.iloc[:,0].values.reshape(5,1)
y = df.iloc[:,1].values

In [ ]:
x.shape

(5, 1)

In [ ]:
x

array([1, 2, 3, 4, 5])

In [ ]:
y

array([2, 4, 5, 4, 5])

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
Lin = LinearRegression()

In [ ]:
Lin.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
Lin.predict([[2.5]])

array([3.7])